### ISSUE TITLE
Need solution to focus the Asset in BIM Image

### ISSUE THREAD

**Issue by castronelson** [GeorgDangl/xbim-meets-angular#4]
I have successfully created upto BIM image display based on Xbim library source.
![image](https://user-images.githubusercontent.com/53040476/65939875-b0679c00-e444-11e9-875b-713db01cdbf9.png)

when i clicked the assets it will zoom exact asset or entity.
these are working fine.

I need to zoom the assets without clicking any assets for ex:

suppose i generated  specific asset from another source to view BIM Image it automatically goes to required asset.How it is possible,could you please understand my requirement?

or else

without clicking any assets i need to default zoom for specific Asset by External Id or some other fields when viewer page loaded.Could you please give me any idea.

**Comment by GeorgDangl** [comment]
Hey @castronelson, thanks for raising this issue!

I think this would be better suited for the official xBim repository at [https://github.com/xBimTeam/XbimWebUI](https://github.com/xBimTeam/XbimWebUI), since this one here is really just an example of how to set up the xBim viewer with an ASP.NET Core backend and an Angular frontend.

The viewer from your screenshot is really just the jQuery based _xBim Browser_, embedded as an example in _xbim-meets-angular_.
