### ISSUE TITLE
How to set Progress bar depends on File Conversion (If large files)?

### ISSUE THREAD

**Issue by castronelson** [GeorgDangl/xbim-meets-angular#5]
Could you please anybody can suggest to set the progress bar (with status messages )with respect to server side loading process . 
eg: Percentage wise showing from starting to end of the conversion

**Comment by GeorgDangl** [comment]
Hey @castronelson, thanks for raising this issue!

I think this would be better suited for the official xBim repository at [https://github.com/xBimTeam/XbimWebUI](https://github.com/xBimTeam/XbimWebUI), since this one here is really just an example of how to set up the xBim viewer with an ASP.NET Core backend and an Angular frontend.

Roughly, I think you need to set up a way to communicate back the model conversion progress from the back end to the front end, so you have to solve two issues:

* How to get the current status of the conversion in the backend? I think there's something available in the Xbim.Geometry package.
* How to communicate this change back to the frontend?

**Comment by GeorgDangl** [comment]
Yeah, SignalR is something that would be suited for this. I've used it before and it would be easy to implement the feature with it. The actual implementation, however, depends heavily on your overall systems architecture and is probably a bit out of scope for the support I can provide for this public demo repository😊

However, just a thought on it generally. Many systems that deal with long running background tasks don't necessarily give you an information about the current, exact progress. Maybe some info like "queued", "in progress" and "finished" could be sufficient for you?

**Comment by castronelson** [comment]
yes.fine.
signalR can be normally used in asp.net technology and windows apps?Could you sure here?

**Comment by GeorgDangl** [comment]
Yes, you can use SignalR both in "old" ASP.NET applications and ASP.NET Core sites. I haven't used it in Desktop applications, but I'm certain that there is a official .NET client available.

**Comment by castronelson** [comment]
okay thanks
